spring:
  application:
    name: customer-management
  #  data:
  #    mongodb:
  #      username: membermanagementadmin
  #      password: password
  #      host: localhost
  #      port: 27019
  #      database: member-management
  #      authentication-database: member-management
  cloud:
    config:
      enabled: false
  jmx:
    enabled: false
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false